### ISSUE TITLE
Add EC2 introduction URLs

### ISSUE THREAD

**Issue by tungbq** [tungbq/AWS-LearningResource#5]
Check the #3 for more detail, and find the template from #3:
For EC2 we have:
## AWS EC2
- Official AWS URL: https://docs.aws.amazon.com/ec2
- Official YouTube Introduction: https://youtu.be/TsRBftzZsQo

**Comment by Project-Xenith** [comment]
Hey, Is this issue open for work?

**Comment by tungbq** [comment]
Sure! Thanks for interesting. I'll assign this to you. Please go ahead

**Comment by Project-Xenith** [comment]
can you please guide me through the process of contributing, this is my
first time contributing. Please give me more details about this issue.

**Comment by tungbq** [comment]
Hey @Project-Xenith please find the contributing guidelines here https://github.com/tungbq/AWS-LearningResource/blob/main/README.md#contributing 
Also you can refer to this similar task here: https://github.com/tungbq/AWS-LearningResource/pull/6/files

**Comment by Project-Xenith** [comment]
Thanks for the help, Will work on this issue by today.

**Comment by tungbq** [comment]
Thanks @Project-Xenith for your contribution!
