### ISSUE TITLE
Add AWS Codecommit

### ISSUE THREAD

**Issue by tungbq** [tungbq/AWS-LearningResource#89]
Append these lines for AWS Codecommit service to services.json:
{
"service_name": "AWS CodeCommit",
"service_url": "https://docs.aws.amazon.com/codecommit",
"service_youtube_url": "https://youtu.be/46PRLMW8otg",
"service_folder_name": "codecommit"
}

**Comment by ThugPigeon653** [comment]
Hey tungbq, does this still need doing? I will put through a pull request

**Comment by tungbq** [comment]
> Hey tungbq, does this still need doing? I will put through a pull request

Sure! Thanks @ThugPigeon653 for your contribution!
